on:
  push:
    branches:
      - "release/*"
name: release
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-title-pattern: "chore: release ${version}"
          release-type: go
          package-name: rudder-sources
          default-branch: ${{ github.ref_name }}
          changelog-types: '
            [
              {
              "type": "feat",
              "section": "Features",
              "hidden": false
              },
              {
              "type": "fix",
              "section": "Bug Fixes",
              "hidden": false
              },
              {
              "type": "chore",
              "section":"Miscellaneous",
              "hidden": false},
              {
              "type": "refactor",
              "section": "Miscellaneous",
              "hidden": false
              },
              {
              "type": "test",
              "section": "Miscellaneous",
              "hidden": false
              },
              {
              "type": "doc",
              "section": "Documentation",
              "hidden": false
              }
            ]'
          extra-files: 'core/version.go'
          bump-minor-pre-major: true
