name: Sync release fix commits to main branch

on:
  pull_request:
    types:
      - closed

jobs:
  sync:
    env:
      GH_TOKEN: ${{ secrets.PAT }}
    if: "${{ github.event.pull_request.merged && startsWith(github.event.pull_request.base.ref, 'release/') && ! startsWith(github.event.pull_request.title, 'chore: release') }}"
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: parse commit
        run: |
          MERGE_COMMIT_SHA=$(gh pr view ${{ github.event.pull_request.number }} --json mergeCommit -q .mergeCommit.oid)
          echo "MERGE_COMMIT_SHA=$MERGE_COMMIT_SHA" >> "$GITHUB_ENV"
      
      - name: create branch
        run: |
          PR_BRANCH="sync-release-fixes-${MERGE_COMMIT_SHA}"
          echo "PR_BRANCH=$PR_BRANCH" >> "$GITHUB_ENV"
          git checkout $MERGE_COMMIT_SHA -b $PR_BRANCH
          git push origin $PR_BRANCH
      
      - name: create pull request
        run: |
          gh pr create \
          --title 'chore: sync #${{ github.event.pull_request.number }} to main branch' \
          --body '# Description' \
          --body '' \
          --body 'Syncing #${{ github.event.pull_request.number }} to main branch' \
          --base main \
          --head $PR_BRANCH \
          --assignee "${{ github.event.pull_request.user.login }}" \
          --label "Enable Test"